### ISSUE TITLE
Gradle failing when MRPA_NASA_API_KEY and MRPA_API_BASE_URL are missing

### ISSUE THREAD

**Issue by javierjmc** [javierjmc/mars-rover-photos#4]
Something that should be explained in the readme is how to compile the code, instructions on how to define `MRPA_NASA_API_KEY` and `MRPA_API_BASE_URL`. 

`MRPA_API_BASE_URL` could be directly defined on gradle, either hardcoded or as a variable within the script, but `MRPA_NASA_API_KEY` should be placed in a secret place as you already did.

However you made it, it should be explain how to make it work for whoever tries to compile the project.

**Comment by JuanByte** [comment]
README updated through PR App/README, waiting for the review to close the issue.
